
BROKER_ADDRESS = '155.185.228.20'
BROKER_PORT = 7883
MQTT_USERNAME = 'dario'
MQTT_PASSWORD = '1234'
MQTT_BASIC_TOPIC = f'/iot/user/{MQTT_USERNAME}'
WEARABLE_TOPIC = 'wearable'
WEARABLE_TELEMETRY_TOPIC = 'telemetry'
WEARABLE_INFO_TOPIC = 'info'
